name: 'Attack on Web action'
description: 'Look for API keys'
inputs:
  repo-name:  # id of input
    description: 'repo name'
    required: true
    default: 'World'
branding:
  icon: 'check'  
  color: 'green'


runs:
  using: 'node12'
  main: 'index.js'
