name: analyzer

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Code Analyzer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Code-Analyzer
        uses: ./ # Uses an action in the root directory
        with:
          repo-name: 'attack-on-web-actions'
        id: hello
      # Use the output from the `hello` step
