on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Code Analyzer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout attack-on-web repository
        uses: actions/checkout@v2
        with:
          repository: felixfaisal/attack-on-web
          path: attack-on-web
      - name: Code-Analyzer
        uses: ./ # Uses an action in the root directory
        id: hello
      # Use the output from the `hello` step
